"""creation table candidatures

Revision ID: 30af119dc295
Revises: 6ddbf0606012
Create Date: 2026-09-05 03:17:57.943342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.types import GUID

# revision identifiers, used by Alembic.
revision: str = '30af119dc295'
down_revision: Union[str, Sequence[str], None] = '6ddbf0606012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatures',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('offre_id', GUID(), nullable=False),
    sa.Column('candidat_id', GUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('recue', 'en_cours', 'entretien', 'refusee', 'acceptee', name='statut_candidature'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidat_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offre_id'], ['offres.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offre_id', 'candidat_id', name='uq_candidature_offre_candidat')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidatures')
    # ### end Alembic commands ###