"""creation table notifications

Revision ID: 39b4e89af1b6
Revises: f68d400373bd
Create Date: 2026-09-06 05:03:12.018536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.types import GUID

# revision identifiers, used by Alembic.
revision: str = '39b4e89af1b6'
down_revision: Union[str, Sequence[str], None] = 'f68d400373bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('type_evenement', sa.String(), nullable=False),
    sa.Column('lue', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###