"""creation table offres

Revision ID: 6ddbf0606012
Revises: e203983b58a6
Create Date: 2026-09-04 19:14:59.700138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.types import GUID

# revision identifiers, used by Alembic.
revision: str = '6ddbf0606012'
down_revision: Union[str, Sequence[str], None] = 'e203983b58a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offres',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('entreprise_id', GUID(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_contrat', sa.Enum('stage', 'cdd', 'cdi', name='type_contrat'), nullable=False),
    sa.Column('competences_obligatoires', sa.Text(), nullable=True),
    sa.Column('competences_souhaitees', sa.Text(), nullable=True),
    sa.Column('soft_skills', sa.Text(), nullable=True),
    sa.Column('niveau_experience', sa.String(), nullable=True),
    sa.Column('disponibilite', sa.String(), nullable=True),
    sa.Column('localisation', sa.String(), nullable=True),
    sa.Column('remuneration', sa.Float(), nullable=True),
    sa.Column('statut', sa.Enum('active', 'expiree', 'archivee', name='statut_offre'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offres')
    # ### end Alembic commands ###