"""creation tables profils entreprise etudiant ecole freelance

Revision ID: e203983b58a6
Revises: 96ec84ce6a54
Create Date: 2026-09-04 18:45:46.307774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.types import GUID

# revision identifiers, used by Alembic.
revision: str = 'e203983b58a6'
down_revision: Union[str, Sequence[str], None] = '96ec84ce6a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecole_profiles',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('nom_etablissement', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('localisation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('entreprise_profiles',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('secteur', sa.String(), nullable=True),
    sa.Column('taille', sa.String(), nullable=True),
    sa.Column('culture', sa.Text(), nullable=True),
    sa.Column('localisation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('freelance_profiles',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('competences', sa.Text(), nullable=True),
    sa.Column('tjm', sa.Float(), nullable=True),
    sa.Column('disponibilite', sa.String(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.Column('annees_experience', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('etudiant_profiles',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('ecole_id', GUID(), nullable=True),
    sa.Column('cv_url', sa.String(), nullable=True),
    sa.Column('competences', sa.Text(), nullable=True),
    sa.Column('experiences', sa.Text(), nullable=True),
    sa.Column('formations', sa.Text(), nullable=True),
    sa.Column('disponibilite', sa.String(), nullable=True),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ecole_id'], ['ecole_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etudiant_profiles')
    op.drop_table('freelance_profiles')
    op.drop_table('entreprise_profiles')
    op.drop_table('ecole_profiles')
    # ### end Alembic commands ###