"""ajout type mission et budget_tjm sur offres

Revision ID: f68d400373bd
Revises: 30af119dc295
Create Date: 2026-09-05 11:22:45.634809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f68d400373bd'
down_revision: Union[str, Sequence[str], None] = '30af119dc295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offres', sa.Column('budget_tjm', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    # Ajout manuel : nouvelle valeur sur l'enum existant (non detecte par autogenerate)
    op.execute("ALTER TYPE type_contrat ADD VALUE IF NOT EXISTS 'mission'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offres', 'budget_tjm')
    # ### end Alembic commands ###
    # Note : PostgreSQL ne permet pas de retirer une valeur d'un enum facilement.
    # Le downgrade ne retire pas 'mission' du type - limitation acceptee pour la V1.