"""ajout role admin et table logs

Revision ID: f6a2b9c6db5d
Revises: 39b4e89af1b6
Create Date: 2026-09-06 14:34:23.711065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.types import GUID

# revision identifiers, used by Alembic.
revision: str = 'f6a2b9c6db5d'
down_revision: Union[str, Sequence[str], None] = '39b4e89af1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('admin_id', GUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('cible_type', sa.String(), nullable=False),
    sa.Column('cible_id', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###